import type { BehavioralPatternsModule } from "./types"

export const BEHAVIORAL_PATTERNS_MODULE: BehavioralPatternsModule = {
  id: "behavioral-patterns",
  name: "Behavioral Patterns",
  description: "Observable behaviors, responses, and interaction patterns that define how patients engage with the world",
  category: "psychological",
  fields: [
    {
      id: "communication_style",
      name: "Communication Style",
      description: "How the patient typically expresses themselves and communicates with others",
      type: "select",
      variable: "{{patient.behavioral_patterns.communication_style}}",
      placeholder: "Select communication style...",
      options: [
        "passive",
        "aggressive",
        "passive_aggressive",
        "assertive",
        "withdrawn",
        "overly_talkative",
        "indirect",
        "direct",
        "defensive",
        "accommodating",
      ],
      sampleData: "passive_aggressive",
      required: true,
      evolvable: true,
      clinicalPurpose:
        "Understanding communication patterns helps therapists adapt their approach and identify areas for skill building. Different therapeutic modalities work better with different communication styles.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "ai_driven", value: 2 },
        probability: { mode: "ai_driven", value: 70 },
        timing: { unit: "session", frequency: 4 },
      },
    },
    {
      id: "conflict_resolution",
      name: "Conflict Resolution Style",
      description: "How the patient typically handles disagreements and interpersonal conflicts",
      type: "select",
      variable: "{{patient.behavioral_patterns.conflict_resolution}}",
      placeholder: "Select conflict resolution style...",
      options: [
        "avoidance",
        "confrontational",
        "collaborative",
        "competitive",
        "accommodating",
        "compromising",
        "withdrawal",
        "explosive",
        "people_pleasing",
        "problem_solving",
      ],
      sampleData: "avoidance",
      required: true,
      evolvable: true,
      clinicalPurpose:
        "Conflict resolution patterns reveal core relationship dynamics and areas for therapeutic intervention. This helps predict how patients will handle therapeutic challenges and relationship issues.",
    },
    {
      id: "decision_making_pattern",
      name: "Decision Making Pattern",
      description: "The patient's typical approach to making choices and decisions",
      type: "select",
      variable: "{{patient.behavioral_patterns.decision_making}}",
      placeholder: "Select decision making pattern...",
      options: [
        "impulsive",
        "overthinking",
        "analytical",
        "intuitive",
        "avoidant",
        "seeks_approval",
        "independent",
        "paralyzed_by_options",
        "quick_decisive",
        "procrastinating",
      ],
      sampleData: "overthinking",
      required: true,
      evolvable: true,
      clinicalPurpose:
        "Decision-making patterns impact all areas of life and therapy progress. Understanding these patterns helps therapists guide patients toward healthier choice-making processes.",
    },
    {
      id: "social_interaction_style",
      name: "Social Interaction Style",
      description: "How the patient typically behaves in social situations and relationships",
      type: "select",
      variable: "{{patient.behavioral_patterns.social_interaction}}",
      placeholder: "Select social interaction style...",
      options: [
        "outgoing",
        "shy",
        "socially_anxious",
        "charismatic",
        "withdrawn",
        "attention_seeking",
        "people_pleasing",
        "dominant",
        "submissive",
        "selective_social",
      ],
      sampleData: "socially_anxious",
      required: true,
      evolvable: true,
      clinicalPurpose:
        "Social interaction patterns reveal attachment styles, self-esteem issues, and social skills deficits. This information guides therapeutic interventions and social skills training.",
    },
    {
      id: "avoidance_behaviors",
      name: "Avoidance Behaviors",
      description: "Specific situations, activities, or experiences the patient tends to avoid",
      type: "list",
      variable: "{{patient.behavioral_patterns.avoidance_behaviors}}",
      placeholder: "Add avoidance behaviors...",
      sampleData: [
        {
          behavior: "Social gatherings with strangers",
          trigger: "Fear of judgment",
          frequency: "Always",
        },
        {
          behavior: "Difficult conversations",
          trigger: "Fear of conflict",
          frequency: "Usually",
        },
        {
          behavior: "New challenges at work",
          trigger: "Fear of failure",
          frequency: "Often",
        },
      ],
      required: false,
      evolvable: true,
      clinicalPurpose:
        "Avoidance behaviors maintain anxiety and prevent growth. Identifying these patterns is crucial for exposure therapy and behavioral interventions.",
    },
    {
      id: "self_care_routines",
      name: "Self-Care Routines",
      description: "Activities and practices the patient engages in for physical and mental well-being",
      type: "list",
      variable: "{{patient.behavioral_patterns.self_care_routines}}",
      placeholder: "Add self-care routines...",
      sampleData: [
        {
          activity: "Evening meditation",
          frequency: "Daily",
          consistency: "Inconsistent",
        },
        {
          activity: "Weekend hiking",
          frequency: "Weekly",
          consistency: "Consistent",
        },
        {
          activity: "Journaling",
          frequency: "Few times per week",
          consistency: "Sporadic",
        },
      ],
      required: false,
      evolvable: true,
      clinicalPurpose:
        "Self-care patterns indicate the patient's relationship with their own well-being and can be built upon or modified to support therapeutic goals.",
    },
    {
      id: "coping_mechanisms",
      name: "Coping Mechanisms",
      description: "Strategies and behaviors the patient uses to manage stress and difficult emotions",
      type: "list",
      variable: "{{patient.behavioral_patterns.coping_mechanisms}}",
      placeholder: "Add coping mechanisms...",
      sampleData: [
        {
          mechanism: "Scrolling social media",
          effectiveness: "Temporarily distracting",
          healthy: false,
        },
        {
          mechanism: "Talking to friends",
          effectiveness: "Very helpful",
          healthy: true,
        },
        {
          mechanism: "Avoiding the situation",
          effectiveness: "Short-term relief",
          healthy: false,
        },
      ],
      required: false,
      evolvable: true,
      clinicalPurpose:
        "Understanding existing coping mechanisms helps therapists identify which strategies to reinforce, modify, or replace with healthier alternatives.",
    },
    {
      id: "stress_response_pattern",
      name: "Stress Response Pattern",
      description: "The patient's typical physiological and behavioral response to stress",
      type: "select",
      variable: "{{patient.behavioral_patterns.stress_response}}",
      placeholder: "Select stress response pattern...",
      options: [
        "fight_response",
        "flight_response",
        "freeze_response",
        "fawn_response",
        "mixed_responses",
        "shutdown",
        "hypervigilance",
        "dissociation",
        "emotional_outbursts",
        "physical_symptoms",
      ],
      sampleData: "freeze_response",
      required: true,
      evolvable: true,
      clinicalPurpose:
        "Stress response patterns indicate trauma history and nervous system regulation. This guides trauma-informed care and somatic interventions.",
    },
    {
      id: "primary_triggers",
      name: "Primary Triggers",
      description: "Situations, people, or experiences that commonly trigger strong emotional reactions",
      type: "multiselect",
      variable: "{{patient.behavioral_patterns.primary_triggers}}",
      placeholder: "Select primary triggers...",
      options: [
        "criticism",
        "rejection",
        "abandonment",
        "conflict",
        "authority_figures",
        "crowds",
        "loud_noises",
        "being_ignored",
        "feeling_trapped",
        "uncertainty",
        "failure",
        "intimacy",
        "being_judged",
        "loss_of_control",
        "financial_stress",
      ],
      sampleData: ["criticism", "rejection", "conflict"],
      required: false,
      evolvable: true,
      clinicalPurpose:
        "Identifying triggers helps predict therapeutic challenges and develop coping strategies. This information is essential for trauma work and emotional regulation training.",
    },
    {
      id: "hobbies_interests",
      name: "Hobbies & Interests",
      description: "Activities the patient enjoys or is interested in, including their level of engagement",
      type: "list",
      variable: "{{patient.behavioral_patterns.hobbies_interests}}",
      placeholder: "Add hobbies and interests...",
      sampleData: [
        {
          activity: "Reading fiction novels",
          engagement_level: "High",
          social_aspect: "Solitary",
        },
        {
          activity: "Playing guitar",
          engagement_level: "Medium",
          social_aspect: "Sometimes with others",
        },
        {
          activity: "Cooking",
          engagement_level: "Low",
          social_aspect: "Family activity",
        },
      ],
      required: false,
      evolvable: true,
      clinicalPurpose:
        "Hobbies and interests reveal strengths, values, and potential therapeutic tools. They can be used for behavioral activation, social connection, and building self-esteem.",
    },
  ],
}
