import type { CognitiveEmotionalPatternsModule } from "./types"

export const COGNITIVE_EMOTIONAL_PATTERNS_MODULE: CognitiveEmotionalPatternsModule = {
  id: "cognitive-emotional-patterns",
  name: "Cognitive & Emotional Patterns",
  description:
    "Internal thought patterns, beliefs, emotions, and self-concept that shape the patient's psychological experience",
  category: "psychological",
  version: "1.0.0",
  fields: [
    {
      id: "core_beliefs",
      name: "Core Beliefs",
      type: "list",
      description:
        "Deep-seated beliefs about self, others, the world, and the future that drive thoughts and behaviors",
      required: true,
      evolvable: true,
      sampleData: [
        {
          belief: "I must be perfect to be worthy of love",
          category: "self",
          strength: "strong",
          origin: "Childhood criticism from parents",
        },
        {
          belief: "People will eventually abandon me",
          category: "others",
          strength: "very_strong",
          origin: "Father left when I was 8",
        },
        {
          belief: "The world is a dangerous place",
          category: "world",
          strength: "moderate",
          origin: "Traumatic car accident at 16",
        },
      ],
      variable: "{{patient.cognitive_emotional_patterns.core_beliefs}}",
      clinicalPurpose:
        "Core beliefs are the foundation of cognitive patterns and emotional responses. Understanding these deep-seated beliefs helps therapists identify the root of many presenting problems and guides cognitive restructuring interventions.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 30 },
        timing: { unit: "session", frequency: 15 },
      },
    },
    {
      id: "core_fears",
      name: "Core Fears",
      type: "multiselect",
      description: "Fundamental fears that drive avoidance behaviors and emotional reactions",
      required: true,
      evolvable: true,
      options: [
        "abandonment",
        "rejection",
        "failure",
        "success",
        "intimacy",
        "judgment",
        "loss_of_control",
        "death_mortality",
        "being_alone",
        "being_trapped",
        "not_being_good_enough",
        "imposter_syndrome",
        "conflict",
        "change",
        "responsibility",
        "being_hurt_again",
        "vulnerability",
        "commitment",
        "disappointing_others",
        "being_seen_as_weak",
      ],
      sampleData: ["abandonment", "judgment", "not_being_good_enough", "failure"],
      variable: "{{patient.cognitive_emotional_patterns.core_fears}}",
      clinicalPurpose:
        "Core fears often underlie anxiety, avoidance behaviors, and relationship difficulties. Identifying these fears helps therapists understand what drives the patient's protective behaviors and emotional reactions.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 40 },
        timing: { unit: "session", frequency: 12 },
      },
    },
    {
      id: "thought_patterns",
      name: "Thought Patterns",
      type: "multiselect",
      description: "Characteristic ways of thinking and processing information",
      required: true,
      evolvable: true,
      options: [
        "all_or_nothing_thinking",
        "catastrophizing",
        "mind_reading",
        "fortune_telling",
        "emotional_reasoning",
        "should_statements",
        "labeling",
        "personalization",
        "mental_filtering",
        "discounting_positive",
        "overgeneralization",
        "rumination",
        "worry_spirals",
        "self_criticism",
        "comparison_to_others",
        "perfectionist_thinking",
        "victim_mentality",
        "black_white_thinking",
        "jumping_to_conclusions",
        "magnification_minimization",
      ],
      sampleData: ["catastrophizing", "mind_reading", "all_or_nothing_thinking", "should_statements"],
      variable: "{{patient.cognitive_emotional_patterns.thought_patterns}}",
      clinicalPurpose:
        "Identifying cognitive distortions and thinking patterns is essential for CBT interventions. These patterns often maintain depression, anxiety, and other mental health symptoms.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 65 },
        timing: { unit: "session", frequency: 6 },
      },
    },
    {
      id: "self_concept",
      name: "Self-Concept",
      type: "list",
      description: "How the patient sees themselves, including identity, strengths, weaknesses, and important roles",
      required: true,
      evolvable: true,
      sampleData: [
        {
          aspect: "identity_description",
          content:
            "I see myself as a caring but anxious person who tries too hard to please everyone. I'm intelligent but often doubt myself.",
        },
        {
          aspect: "strengths_perceived",
          content: "Empathetic, Hardworking, Creative, Loyal",
        },
        {
          aspect: "weaknesses_perceived",
          content: "Too sensitive, Indecisive, Perfectionist, Anxious",
        },
        {
          aspect: "roles_important",
          content: "Daughter, Friend, Student, Caregiver",
        },
      ],
      variable: "{{patient.cognitive_emotional_patterns.self_concept}}",
      clinicalPurpose:
        "Self-concept affects how patients interpret experiences and relate to others. Understanding their self-perception helps therapists address self-esteem issues and identity concerns.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 55 },
        timing: { unit: "session", frequency: 8 },
      },
    },
    {
      id: "emotional_regulation_style",
      name: "Emotional Regulation Style",
      type: "select",
      description: "Primary way the patient manages and processes emotions",
      required: true,
      evolvable: true,
      placeholder: "Select emotional regulation style...",
      options: [
        "emotional_suppression",
        "emotional_expression",
        "healthy_processing",
        "emotional_avoidance",
        "emotional_overwhelm",
        "compartmentalization",
        "seeking_support",
        "self_soothing",
        "distraction_based",
        "problem_focused_coping",
        "rumination_based",
        "explosive_release",
      ],
      sampleData: "emotional_suppression",
      variable: "{{patient.cognitive_emotional_patterns.emotional_regulation_style}}",
      clinicalPurpose:
        "How patients manage emotions affects their mental health and relationships. Understanding their regulation style guides interventions for emotional skills development.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 70 },
        timing: { unit: "session", frequency: 5 },
      },
    },
    {
      id: "primary_emotions",
      name: "Primary Emotions",
      type: "multiselect",
      description: "Most frequently experienced emotions that characterize the patient's emotional landscape",
      required: true,
      evolvable: true,
      options: [
        "anxiety",
        "sadness",
        "anger",
        "fear",
        "shame",
        "guilt",
        "joy",
        "excitement",
        "contentment",
        "frustration",
        "loneliness",
        "hope",
        "love",
        "gratitude",
        "overwhelm",
        "numbness",
        "irritability",
        "disappointment",
        "confusion",
        "emptiness",
      ],
      sampleData: ["anxiety", "sadness", "shame", "overwhelm"],
      variable: "{{patient.cognitive_emotional_patterns.primary_emotions}}",
      clinicalPurpose:
        "Understanding predominant emotions helps therapists focus on emotional processing and regulation skills most relevant to the patient's experience.",
      evolution: {
        enabled: true,
        type: "bidirectional",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 50 },
        timing: { unit: "session", frequency: 4 },
      },
    },
    {
      id: "emotional_triggers",
      name: "Emotional Triggers",
      type: "list",
      description: "Specific situations, events, or stimuli that consistently provoke strong emotional reactions",
      required: false,
      evolvable: true,
      sampleData: [
        {
          trigger: "Being criticized or corrected",
          emotion: "Shame",
          intensity: "overwhelming",
          context: "Especially at work or in relationships",
        },
        {
          trigger: "Feeling excluded from social situations",
          emotion: "Sadness",
          intensity: "strong",
          context: "Reminds me of childhood bullying",
        },
        {
          trigger: "Making mistakes",
          emotion: "Anxiety",
          intensity: "moderate",
          context: "Fear of disappointing others",
        },
      ],
      variable: "{{patient.cognitive_emotional_patterns.emotional_triggers}}",
      clinicalPurpose:
        "Emotional triggers help predict when patients will struggle and guide development of coping strategies for specific situations.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 45 },
        timing: { unit: "session", frequency: 10 },
      },
    },
    {
      id: "self_esteem_pattern",
      name: "Self-Esteem Pattern",
      type: "list",
      description: "Patterns related to self-worth, validation sources, and self-esteem stability",
      required: true,
      evolvable: true,
      sampleData: [
        {
          aspect: "baseline_level",
          content: "Low - generally negative self-view",
        },
        {
          aspect: "stability",
          content: "Unstable - fluctuates based on external feedback",
        },
        {
          aspect: "conditional_factors",
          content: "Academic performance, Others' approval, Physical appearance",
        },
        {
          aspect: "sources_of_validation",
          content: "External praise, Achievement, Helping others",
        },
      ],
      variable: "{{patient.cognitive_emotional_patterns.self_esteem_pattern}}",
      clinicalPurpose:
        "Self-esteem patterns affect mood, relationships, and life choices. Understanding these patterns guides interventions for building stable, internal self-worth.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 35 },
        timing: { unit: "session", frequency: 12 },
      },
    },
    {
      id: "internal_dialogue",
      name: "Internal Dialogue",
      type: "textarea",
      description: "The tone, content, and characteristics of the patient's inner voice and self-talk",
      required: true,
      evolvable: true,
      placeholder: "Describe the typical tone and content of their inner voice...",
      sampleData:
        "My inner voice is very critical and harsh. It constantly tells me I'm not doing enough, that I'll mess things up, and that people are judging me. It's like having a mean critic in my head that never takes a break. Sometimes it sounds like my mother's voice when she was disappointed in me.",
      variable: "{{patient.cognitive_emotional_patterns.internal_dialogue}}",
      clinicalPurpose:
        "Internal dialogue reveals the patient's relationship with themselves and often mirrors early relationships. Understanding this helps with self-compassion and cognitive work.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 60 },
        timing: { unit: "session", frequency: 7 },
      },
    },
    {
      id: "cognitive_distortions",
      name: "Cognitive Distortions",
      type: "multiselect",
      description: "Specific thinking errors and biases that contribute to emotional distress",
      required: true,
      evolvable: true,
      options: [
        "all_or_nothing_thinking",
        "overgeneralization",
        "mental_filter",
        "disqualifying_positive",
        "jumping_to_conclusions",
        "magnification_minimization",
        "emotional_reasoning",
        "should_statements",
        "labeling",
        "personalization",
        "fortune_telling",
        "mind_reading",
        "catastrophizing",
        "comparison_trap",
        "perfectionism",
        "blame_game",
        "control_fallacies",
        "fallacy_of_fairness",
        "always_being_right",
        "heavens_reward_fallacy",
      ],
      sampleData: ["all_or_nothing_thinking", "should_statements", "mind_reading", "catastrophizing"],
      variable: "{{patient.cognitive_emotional_patterns.cognitive_distortions}}",
      clinicalPurpose:
        "Cognitive distortions maintain negative emotions and maladaptive behaviors. Identifying these is crucial for CBT interventions and cognitive restructuring.",
      evolution: {
        enabled: true,
        type: "improvement",
        amount: { mode: "manual", value: 1 },
        probability: { mode: "manual", value: 75 },
        timing: { unit: "session", frequency: 4 },
      },
    },
  ],
}

// Export for backward compatibility and different use cases
export const cognitiveEmotionalPatternsConfig = COGNITIVE_EMOTIONAL_PATTERNS_MODULE
export default COGNITIVE_EMOTIONAL_PATTERNS_MODULE
