import type { ModuleField } from "@/lib/database-schema"

export const FAMILY_DYNAMICS_MODULE = {
  id: "family_dynamics",
  name: "Family Dynamics",
  description: "Family relationships, history, and dynamics that shape the patient's worldview",
  version: "1.0.0",
  category: "social" as const,
  fields: [
    {
      id: "family_structure",
      name: "Family Structure",
      description: "Current family composition and structure",
      type: "select" as const,
      required: true,
      evolvable: false,
      sampleData: "nuclear_family",
      options: [
        "nuclear_family",
        "single_parent",
        "blended_family",
        "extended_family",
        "adoptive_family",
        "foster_family",
        "chosen_family",
        "no_family_contact",
        "other",
      ],
      placeholder: "Select family structure...",
      clinicalPurpose:
        "Understanding family structure helps assess support systems, relationship patterns, and potential stressors in the patient's life.",
    },
    {
      id: "family_members",
      name: "Family Members",
      description: "Key family members and their relationships with the patient",
      type: "list" as const,
      required: true,
      evolvable: true,
      sampleData: [
        {
          name: "Margaret Thompson",
          relationship: "Mother",
          age: 58,
          living_status: "alive",
          relationship_quality: "close",
          contact_frequency: "weekly",
          description: "Supportive but sometimes overprotective. Retired teacher who worries about my career choices.",
        },
        {
          name: "Robert Thompson",
          relationship: "Father",
          age: 62,
          living_status: "alive",
          relationship_quality: "distant",
          contact_frequency: "monthly",
          description: "Emotionally unavailable. Works long hours, struggles to express emotions or connect.",
        },
      ],
      placeholder: "Add family members...",
      clinicalPurpose:
        "Mapping family relationships reveals attachment patterns, support systems, and potential sources of stress or healing.",
    },
    {
      id: "primary_caregiver_childhood",
      name: "Primary Caregiver in Childhood",
      description: "Who was the main caregiver during formative years",
      type: "text" as const,
      required: true,
      evolvable: false,
      sampleData: "Mother (Margaret) was primary caregiver. Father worked long hours and was emotionally distant.",
      placeholder: "Describe primary caregiver relationship...",
      clinicalPurpose:
        "Primary caregiver relationships form the foundation of attachment styles and emotional regulation patterns.",
    },
    {
      id: "childhood_family_environment",
      name: "Childhood Family Environment",
      description: "Overall atmosphere and dynamics in childhood home",
      type: "textarea" as const,
      required: true,
      evolvable: false,
      sampleData:
        "Generally stable but emotionally reserved household. High expectations for academic achievement. Limited emotional expression or discussion of feelings. Mother was nurturing but anxious. Father was provider but emotionally unavailable.",
      placeholder: "Describe the emotional climate, communication patterns, and overall atmosphere...",
      clinicalPurpose:
        "Childhood environment shapes emotional development, coping mechanisms, and relationship expectations in adulthood.",
    },
    {
      id: "family_communication_style",
      name: "Family Communication Style",
      description: "How family members typically communicate with each other",
      type: "select" as const,
      required: true,
      evolvable: true,
      sampleData: "indirect_avoidant",
      options: [
        "open_direct",
        "indirect_avoidant",
        "conflict_avoidant",
        "aggressive_confrontational",
        "passive_aggressive",
        "emotional_expressive",
        "logical_rational",
        "chaotic_unpredictable",
        "silent_withdrawn",
      ],
      placeholder: "Select communication style...",
      clinicalPurpose:
        "Communication patterns learned in family of origin often persist in adult relationships and therapeutic interactions.",
    },
    {
      id: "family_roles_patient",
      name: "Patient's Role in Family",
      description: "What roles or functions the patient served in their family system",
      type: "multiselect" as const,
      required: true,
      evolvable: true,
      sampleData: ["peacemaker", "high_achiever", "responsible_one"],
      options: [
        "peacemaker",
        "scapegoat",
        "golden_child",
        "lost_child",
        "mascot_entertainer",
        "caretaker",
        "responsible_one",
        "rebel",
        "high_achiever",
        "mediator",
        "protector",
        "confidant",
        "parentified_child",
      ],
      placeholder: "Select family roles...",
      clinicalPurpose:
        "Family roles reveal learned behavioral patterns, responsibilities, and identity formation that impact adult functioning.",
    },
    {
      id: "family_mental_health_history",
      name: "Family Mental Health History",
      description: "Known mental health conditions or concerns in family members",
      type: "multiselect" as const,
      required: false,
      evolvable: false,
      sampleData: ["anxiety_disorders", "depression"],
      options: [
        "no_known_history",
        "depression",
        "anxiety_disorders",
        "bipolar_disorder",
        "schizophrenia",
        "personality_disorders",
        "eating_disorders",
        "substance_abuse",
        "suicide_attempts",
        "domestic_violence",
        "child_abuse",
        "trauma_ptsd",
        "learning_disabilities",
        "autism_spectrum",
        "adhd",
      ],
      placeholder: "Select family mental health history...",
      clinicalPurpose:
        "Family mental health history provides context for genetic predispositions, learned behaviors, and environmental factors.",
    },
    {
      id: "family_cultural_background",
      name: "Family Cultural Background",
      description: "Cultural, ethnic, or religious background that influences family dynamics",
      type: "textarea" as const,
      required: false,
      evolvable: false,
      sampleData:
        "Irish-Catholic background with strong emphasis on education and 'keeping family business private.' Traditional gender roles were expected. Mental health was stigmatized and not discussed openly.",
      placeholder: "Describe cultural influences on family dynamics...",
      clinicalPurpose:
        "Cultural context helps understand family values, communication patterns, and attitudes toward mental health and help-seeking.",
    },
    {
      id: "family_traditions_values",
      name: "Family Traditions & Values",
      description: "Important family traditions, values, or beliefs that shaped the patient",
      type: "multiselect" as const,
      required: false,
      evolvable: false,
      sampleData: ["education_achievement", "hard_work", "family_loyalty", "emotional_restraint"],
      options: [
        "education_achievement",
        "hard_work",
        "family_loyalty",
        "religious_faith",
        "financial_security",
        "social_status",
        "independence",
        "emotional_restraint",
        "helping_others",
        "creativity_expression",
        "physical_health",
        "community_service",
        "tradition_heritage",
        "honesty_integrity",
        "competition_success",
      ],
      placeholder: "Select family values...",
      clinicalPurpose:
        "Family values shape identity, goals, and internal conflicts when personal desires conflict with family expectations.",
    },
    {
      id: "current_living_situation",
      name: "Current Living Situation",
      description: "Current living arrangements and family proximity",
      type: "text" as const,
      required: true,
      evolvable: true,
      sampleData: "Lives alone in apartment, 2 hours from parents. Sees parents monthly, talks to mother weekly.",
      placeholder: "Describe current living situation and family contact...",
      clinicalPurpose:
        "Current family proximity and contact patterns reveal ongoing family influence and support availability.",
    },
    {
      id: "family_support_level",
      name: "Family Support Level",
      description: "How supportive family is of patient's current life and challenges",
      type: "select" as const,
      required: true,
      evolvable: true,
      sampleData: "somewhat_supportive",
      options: [
        "very_supportive",
        "somewhat_supportive",
        "neutral_uninvolved",
        "somewhat_unsupportive",
        "very_unsupportive",
        "actively_harmful",
        "no_contact",
      ],
      placeholder: "Select support level...",
      clinicalPurpose:
        "Family support level impacts treatment planning, crisis resources, and therapeutic goals around family relationships.",
    },
    {
      id: "family_conflicts",
      name: "Current Family Conflicts",
      description: "Ongoing conflicts or tensions within the family system",
      type: "list" as const,
      required: false,
      evolvable: true,
      sampleData: [
        {
          participants: "Patient and Father",
          issue: "Career choices and life direction",
          duration: "2 years",
          resolution_status: "ongoing",
          impact_on_patient: "Creates anxiety and self-doubt about life choices",
        },
      ],
      placeholder: "Add family conflicts...",
      clinicalPurpose:
        "Current conflicts reveal ongoing stressors, relationship patterns, and potential areas for therapeutic intervention.",
    },
    {
      id: "childhood_memories",
      name: "Significant Childhood Memories",
      description: "Important memories that shaped the patient's view of family and relationships",
      type: "list" as const,
      required: false,
      evolvable: false,
      sampleData: [
        {
          age_range: "8-10 years old",
          memory_type: "negative",
          description: "Parents fighting about money late at night, trying to pretend everything was fine the next day",
          emotional_impact: "Learned to be hypervigilant about family tension and to suppress own needs",
        },
      ],
      placeholder: "Add significant memories...",
      clinicalPurpose:
        "Childhood memories reveal formative experiences that continue to influence current emotional responses and relationship patterns.",
    },
    {
      id: "family_secrets_issues",
      name: "Family Secrets or Hidden Issues",
      description: "Unspoken issues, secrets, or 'elephants in the room' within the family",
      type: "textarea" as const,
      required: false,
      evolvable: false,
      sampleData:
        "Father's drinking problem was never directly addressed. Mother's anxiety and depression were minimized. Financial stress was hidden from children but created tension.",
      placeholder: "Describe any family secrets or unaddressed issues...",
      clinicalPurpose:
        "Family secrets reveal patterns of avoidance, shame, and communication dysfunction that often persist in adult relationships.",
    },
    {
      id: "family_financial_situation",
      name: "Family Financial Background",
      description: "Financial circumstances and attitudes toward money in family of origin",
      type: "select" as const,
      required: false,
      evolvable: false,
      sampleData: "middle_class_stable",
      options: [
        "wealthy_secure",
        "upper_middle_class",
        "middle_class_stable",
        "middle_class_struggling",
        "working_class",
        "low_income",
        "poverty",
        "financial_instability",
        "financial_trauma",
      ],
      placeholder: "Select financial background...",
      clinicalPurpose:
        "Financial background influences attitudes toward security, success, and self-worth, and may contribute to current stressors.",
    },
    {
      id: "family_education_values",
      name: "Family Attitude Toward Education",
      description: "How much family valued education and learning",
      type: "select" as const,
      required: false,
      evolvable: false,
      sampleData: "highly_valued",
      options: [
        "highly_valued",
        "moderately_valued",
        "neutral",
        "undervalued",
        "actively_discouraged",
        "mixed_messages",
      ],
      placeholder: "Select education values...",
      clinicalPurpose:
        "Educational values reveal family priorities and may contribute to achievement pressure or imposter syndrome.",
    },
  ] as ModuleField[],
}
