import type { WorkCareerModule } from "./types"

export const WORK_CAREER_MODULE: WorkCareerModule = {
  id: "work_career",
  name: "Work & Career",
  description: "Professional life, career goals, and work-related stress patterns",
  category: "lifestyle",
  version: "1.0.0",
  fields: [
    {
      id: "employment_status",
      name: "Employment Status",
      type: "select",
      description: "Current employment situation and work status",
      required: true,
      evolvable: true,
      variable: "{{patient.work_career.employment_status}}",
      sampleData: "full_time_employed",
      clinicalPurpose:
        "Understanding employment status helps assess financial stability, daily structure, social connections, and potential sources of stress or fulfillment. Changes in employment can significantly impact mental health.",
      placeholder: "Select employment status...",
      options: [
        "full_time_employed",
        "part_time_employed",
        "self_employed",
        "unemployed_seeking",
        "unemployed_not_seeking",
        "student",
        "retired",
        "disabled_unable_to_work",
        "homemaker",
        "volunteer_work",
      ],
    },
    {
      id: "job_title",
      name: "Job Title/Role",
      type: "text",
      description: "Current or most recent job title and role",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.job_title}}",
      sampleData: "Marketing Coordinator",
      clinicalPurpose:
        "Job title provides insight into professional identity, skill level, responsibility, and potential workplace stressors. It helps understand the patient's professional context and self-concept.",
      placeholder: "Enter job title or role...",
    },
    {
      id: "job_satisfaction",
      name: "Job Satisfaction",
      type: "select",
      description: "Overall satisfaction with current or recent work",
      required: true,
      evolvable: true,
      variable: "{{patient.work_career.job_satisfaction}}",
      sampleData: "somewhat_dissatisfied",
      clinicalPurpose:
        "Job satisfaction directly impacts mental health, self-esteem, and life satisfaction. Low job satisfaction can contribute to depression, anxiety, and relationship problems.",
      placeholder: "Select satisfaction level...",
      options: [
        "very_satisfied",
        "satisfied",
        "somewhat_satisfied",
        "neutral",
        "somewhat_dissatisfied",
        "dissatisfied",
        "very_dissatisfied",
      ],
    },
    {
      id: "work_stress_sources",
      name: "Work-Related Stress Sources",
      type: "multiselect",
      description: "Specific sources of stress in the workplace",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.work_stress_sources}}",
      sampleData: ["heavy_workload", "difficult_colleagues", "job_insecurity"],
      clinicalPurpose:
        "Identifying specific work stressors helps develop targeted coping strategies and understand triggers for anxiety, depression, or other mental health symptoms.",
      options: [
        "heavy_workload",
        "tight_deadlines",
        "difficult_colleagues",
        "poor_management",
        "job_insecurity",
        "lack_of_recognition",
        "insufficient_pay",
        "long_commute",
        "work_life_imbalance",
        "lack_of_growth_opportunities",
        "workplace_conflict",
        "unclear_expectations",
        "toxic_work_environment",
        "physical_demands",
        "emotional_demands",
      ],
    },
    {
      id: "career_goals",
      name: "Career Goals",
      type: "textarea",
      description: "Professional aspirations and career objectives",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.career_goals}}",
      sampleData:
        "I want to advance to a senior marketing role within the next 3 years, ideally with more creative freedom and better work-life balance. Long-term, I'd like to start my own consulting business.",
      clinicalPurpose:
        "Career goals reveal motivation, self-efficacy, future orientation, and values. Misalignment between goals and reality can cause distress, while clear goals can provide direction and hope.",
      placeholder: "Describe your career goals and aspirations...",
    },
    {
      id: "work_life_balance",
      name: "Work-Life Balance",
      type: "select",
      description: "Assessment of balance between work and personal life",
      required: true,
      evolvable: true,
      variable: "{{patient.work_career.work_life_balance}}",
      sampleData: "poor",
      clinicalPurpose:
        "Work-life balance significantly impacts mental health, relationships, and overall well-being. Poor balance can lead to burnout, relationship problems, and physical health issues.",
      placeholder: "Select work-life balance...",
      options: ["excellent", "very_good", "good", "fair", "poor", "very_poor"],
    },
    {
      id: "workplace_relationships",
      name: "Workplace Relationships",
      type: "textarea",
      description: "Quality and nature of relationships with colleagues and supervisors",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.workplace_relationships}}",
      sampleData:
        "I get along well with most of my coworkers, but I have ongoing conflicts with my direct supervisor. She micromanages and rarely gives positive feedback. I feel isolated from the team sometimes.",
      clinicalPurpose:
        "Workplace relationships affect daily stress, job satisfaction, and social support. Poor relationships can contribute to anxiety, depression, and workplace avoidance behaviors.",
      placeholder: "Describe your relationships with colleagues and supervisors...",
    },
    {
      id: "professional_challenges",
      name: "Professional Challenges",
      type: "multiselect",
      description: "Current obstacles and difficulties in professional life",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.professional_challenges}}",
      sampleData: ["skill_gaps", "imposter_syndrome", "networking_difficulties"],
      clinicalPurpose:
        "Professional challenges help identify areas for growth, sources of anxiety, and potential therapeutic targets. Understanding these challenges can guide skill-building and confidence-building interventions.",
      options: [
        "skill_gaps",
        "lack_of_experience",
        "imposter_syndrome",
        "networking_difficulties",
        "public_speaking_anxiety",
        "leadership_challenges",
        "technology_adaptation",
        "industry_changes",
        "competition",
        "discrimination",
        "age_related_barriers",
        "educational_limitations",
        "geographic_limitations",
        "family_obligations",
        "health_limitations",
      ],
    },
    {
      id: "career_history",
      name: "Career History",
      type: "list",
      description: "Previous employment experiences and career progression",
      required: false,
      evolvable: false,
      variable: "{{patient.work_career.career_history}}",
      sampleData: [
        {
          company: "ABC Marketing Agency",
          position: "Junior Marketing Assistant",
          duration: "2 years",
          reason_for_leaving: "Sought better growth opportunities",
        },
        {
          company: "XYZ Corporation",
          position: "Marketing Specialist",
          duration: "1.5 years",
          reason_for_leaving: "Company downsizing",
        },
      ],
      clinicalPurpose:
        "Career history reveals patterns of job stability, growth, decision-making, and potential triggers for stress or change. It helps understand the patient's professional journey and resilience.",
    },
    {
      id: "financial_stress",
      name: "Financial Stress Related to Work",
      type: "select",
      description: "Level of financial stress related to work and income",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.financial_stress}}",
      sampleData: "moderate",
      clinicalPurpose:
        "Financial stress significantly impacts mental health, relationships, and life choices. Understanding work-related financial concerns helps address anxiety, depression, and decision-making difficulties.",
      placeholder: "Select financial stress level...",
      options: ["none", "minimal", "mild", "moderate", "significant", "severe", "overwhelming"],
    },
    {
      id: "work_environment_preferences",
      name: "Work Environment Preferences",
      type: "multiselect",
      description: "Preferred work settings and environmental factors",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.work_environment_preferences}}",
      sampleData: ["remote_work", "flexible_schedule", "collaborative_team"],
      clinicalPurpose:
        "Understanding work environment preferences helps identify sources of satisfaction or dissatisfaction, and can guide career decisions and workplace accommodations for mental health.",
      options: [
        "remote_work",
        "office_based",
        "hybrid_work",
        "flexible_schedule",
        "structured_schedule",
        "collaborative_team",
        "independent_work",
        "creative_environment",
        "fast_paced",
        "calm_environment",
        "leadership_opportunities",
        "mentoring_others",
        "continuous_learning",
        "stable_routine",
        "variety_and_change",
      ],
    },
    {
      id: "professional_identity",
      name: "Professional Identity",
      type: "textarea",
      description: "How the patient sees themselves professionally and their work-related self-concept",
      required: false,
      evolvable: true,
      variable: "{{patient.work_career.professional_identity}}",
      sampleData:
        "I see myself as a creative problem-solver who thrives in collaborative environments. I value making a meaningful impact through my work, but I sometimes struggle with confidence in my abilities. Work is important to me, but I don't want it to define my entire identity.",
      clinicalPurpose:
        "Professional identity affects self-esteem, life satisfaction, and career decisions. Understanding how patients view themselves professionally helps address identity issues, confidence problems, and work-life integration.",
      placeholder: "Describe how you see yourself professionally and what work means to you...",
    },
  ],
}

// Export individual components for backward compatibility
export const workCareerFields = WORK_CAREER_MODULE.fields
export const workCareerModule = WORK_CAREER_MODULE
export default WORK_CAREER_MODULE
